# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-16 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.TextField(null=True)),
                ('cif', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, null=True)),
                ('n_factura', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('base_imponible', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, null=True)),
                ('n_factura', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('base_imponible', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aita.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.TextField(null=True)),
                ('cif', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='gasto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aita.Proveedor'),
        ),
    ]
