# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-21 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aita', '0002_auto_20180421_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='gasto',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='ingreso',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre']},
        ),
    ]
